version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: cimg/ruby:2.7.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.28.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
         name: security
         command: docker-compose run --rm metadata-app bundle exec brakeman -q --no-pager
      - run:
          name: lint
          command: docker-compose run --rm metadata-app bundle exec rubocop
      - run:
          name: test
          command: make spec
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: main
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-metadata-api
    docker: &ecr_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys: &ssh_keys
          fingerprints:
            - a9:9c:0f:a2:2f:77:41:80:b8:84:e0:c8:10:a4:eb:2e
      - run: &base_environment_variables
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_a99c0fa22f774180b884e0c810a4eb2e" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to test
          environment:
            APPLICATION_NAME: fb-metadata-api
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-saas-test
          command: './deploy-scripts/bin/deploy'
      - run:
          name: deploy to test environment in EKS
          environment:
            APPLICATION_NAME: fb-metadata-api
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-saas-test
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status:
          only_for_branches: main
          success_message: ":rocket:  Successfully deployed to Test  :guitar:"
          failure_message: ":alert:  Failed to deploy to Test  :try_not_to_cry:"
          include_job_number_field: false
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-metadata-api
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: live
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to live
          environment:
            APPLICATION_NAME: fb-metadata-api
            PLATFORM_ENV: live
            K8S_NAMESPACE: formbuilder-saas-live
          command: './deploy-scripts/bin/deploy'
      - slack/status:
          only_for_branches: main
          success_message: ":rocket:  Successfully deployed to Live  :guitar:"
          failure_message: ":alert:  Failed to deploy to Live  :try_not_to_cry:"
          include_job_number_field: false
  editor_acceptance_tests:
    docker:
      - image: cimg/ruby:2.7.5
      - environment: &acceptance_tests_docker_environment
          POSTGRES_DB: editor_local
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        image: 'circleci/postgres:12.4'
    resource_class: large
    environment: &acceptance_tests_environment
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: password
      PGUSER: postgres
      RAILS_ENV: test
    parallelism: 5
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check browser tools install
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Run editor acceptance tests
          command: |
            EDITOR_APP=https://fb-editor-test.apps.live-1.cloud-platform.service.justice.gov.uk
            echo 'export ACCEPTANCE_TESTS_EDITOR_APP=$EDITOR_APP' >> $BASH_ENV
            echo 'export ACCEPTANCE_TESTS_USER=$ACCEPTANCE_TESTS_USER' >> $BASH_ENV
            echo 'export ACCEPTANCE_TESTS_PASSWORD=$ACCEPTANCE_TESTS_PASSWORD' >> $BASH_ENV
            echo 'export CI_MODE=true' >> $BASH_ENV
            source $BASH_ENV

            git clone https://github.com/ministryofjustice/fb-editor
            cd fb-editor

            bundle install
            bundle exec rails db:setup
            bundle exec rails db:migrate

            TESTFILES=$(circleci tests glob "acceptance/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=filename)
            TO_EXCLUDE=acceptance/features/no_branching_spec.rb
            FILTERED_TESTFILES=$(printf '%s\n' "${TESTFILES//$TO_EXCLUDE/}")
            echo '***********'
            echo $FILTERED_TESTFILES
            echo '***********'

            bundle exec rspec --format progress \
              --format RspecJunitFormatter \
              --out ~/acceptance/acceptance.xml \
              $FILTERED_TESTFILES
      - store_test_results:
          path: ~/acceptance
      - slack/status: *slack_status
  editor_acceptance_tests_no_branching:
    docker:
      - image: cimg/ruby:2.7.5
      - environment: *acceptance_tests_docker_environment
        image: 'circleci/postgres:12.4'
    resource_class: large
    environment: *acceptance_tests_environment
    steps:
      - browser-tools/install-browser-tools
      - run:
          name: Check browser tools install
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Run editor acceptance tests
          command: |
            EDITOR_APP=https://fb-editor-test-no-branching.apps.live-1.cloud-platform.service.justice.gov.uk
            echo 'export ACCEPTANCE_TESTS_EDITOR_APP=$EDITOR_APP' >> $BASH_ENV
            echo 'export ACCEPTANCE_TESTS_USER=$ACCEPTANCE_TESTS_USER' >> $BASH_ENV
            echo 'export ACCEPTANCE_TESTS_PASSWORD=$ACCEPTANCE_TESTS_PASSWORD' >> $BASH_ENV
            echo 'export CI_MODE=true' >> $BASH_ENV
            source $BASH_ENV

            git clone https://github.com/ministryofjustice/fb-editor
            cd fb-editor

            bundle install
            bundle exec rails db:setup
            bundle exec rails db:migrate

            bundle exec rspec --format progress \
              --format RspecJunitFormatter \
              acceptance/features/no_branching_spec.rb
      - slack/status: *slack_status

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_deploy_to_test:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - editor_acceptance_tests:
          requires:
            - build_and_deploy_to_test
      - editor_acceptance_tests_no_branching:
          requires:
            - build_and_deploy_to_test
      - slack/approval-notification:
          message: ":portalorangeparrot:  Deployment to Live pending approval  :portalblueparrot:"
          include_job_number_field: false
          requires:
            - editor_acceptance_tests
            - editor_acceptance_tests_no_branching
      - confirm_live_deploy:
          type: approval
          requires:
            - editor_acceptance_tests
            - editor_acceptance_tests_no_branching
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
