version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.4.3
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  login-to-aws:
    docker: &docker_image
      - image: 'cimg/ruby:3.1.3-node'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION # this will use the env var
      - run: &ecr_login
          name: Login to ecr
          command: |
            aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
            aws configure export-credentials --format env
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env

  build:
    docker:
      - image: 'cimg/ruby:3.1.3'
    steps:
      - checkout
      - ruby/install-deps
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: main
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  lint:
    docker:
      - image: 'cimg/ruby:3.1.3'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: running rubocop
      - slack/status: *slack_status
  security:
    docker:
      - image: 'cimg/ruby:3.1.3'
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec brakeman -q --no-pager
      - slack/status: *slack_status
  test:
    working_directory: ~/circle
    docker:
      - image: cimg/ruby:3.1.3
    steps:
      - checkout
      - setup_remote_docker: &remote_docker
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.28.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: test
          command: make spec
      - slack/status: *slack_status
  build_and_push_image:
    working_directory: ~/circle/git/fb-metadata-api
    docker: &ecr_image
      - image: docker.io/ministryofjustice/fb-builder:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - attach_workspace:
          at: .
      - run: &workspace_envs
          command: |
            cat bash.env >> $BASH_ENV
      - run: &base_environment_variables
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_d8c6c158ff1732a896f283a6e7e7e838" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone --branch temporary-ecr-creds git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
  deploy_to_test_eks:
    working_directory: ~/circle/git/fb-metadata-api
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - add_ssh_keys: &ssh_keys
          fingerprints:
            - d8:c6:c1:58:ff:17:32:a8:96:f2:83:a6:e7:e7:e8:38
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to test environment in EKS
          environment:
            APPLICATION_NAME: fb-metadata-api
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-saas-test
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status
  deploy_to_live_eks:
    working_directory: ~/circle/git/fb-metadata-api
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to live (eks)
          environment:
            APPLICATION_NAME: fb-metadata-api
            PLATFORM_ENV: live
            K8S_NAMESPACE: formbuilder-saas-live
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status:
          only_for_branches: main
          success_message: ":rocket:  Successfully deployed to Live (eks)  :guitar:"
          failure_message: ":alert:  Failed to deploy to Live (eks)  :try_not_to_cry:"
          include_job_number_field: false
  editor_acceptance_tests_eks:
    docker:
      - image: cimg/ruby:3.1.3
      - environment:
          POSTGRES_DB: editor_local
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        image: 'cimg/postgres:12.9'
    resource_class: large
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: password
      PGUSER: postgres
      RAILS_ENV: test
    parallelism: 4
    steps:
      - checkout
      - run: sudo apt-get update
      - browser-tools/install-chrome:
          # TODO remove following line when fixed https://github.com/CircleCI-Public/browser-tools-orb/issues/90
          chrome-version: 116.0.5845.96
      - browser-tools/install-chromedriver
      - run:
          name: Check browser tools install
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Run editor acceptance tests (eks)
          command: |
            EDITOR_APP=https://testable-metadata-presenter.apps.live.cloud-platform.service.justice.gov.uk
            echo 'export ACCEPTANCE_TESTS_EDITOR_APP=$EDITOR_APP' >> $BASH_ENV
            echo 'export ACCEPTANCE_TESTS_USER=$ACCEPTANCE_TESTS_USER' >> $BASH_ENV
            echo 'export ACCEPTANCE_TESTS_PASSWORD=$ACCEPTANCE_TESTS_PASSWORD' >> $BASH_ENV
            echo 'export CI_MODE=true' >> $BASH_ENV
            source $BASH_ENV

            git clone https://github.com/ministryofjustice/fb-editor
            cd fb-editor

            bundle install
            bundle exec rails db:setup
            bundle exec rails db:migrate

            TESTFILES=$(circleci tests glob "acceptance/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=filename)
            echo '***********'
            echo $TESTFILES
            echo '***********'

            bundle exec rspec --format progress \
              --format RspecJunitFormatter \
              --out ~/acceptance/acceptance.xml \
              $TESTFILES
      - store_test_results:
          path: ~/acceptance
      - slack/status: *slack_status

workflows:
  version: 2
  test_and_build:
    jobs:
      - login-to-aws:
          context: &context
            - moj-forms
      - build:
          requires:
            - login-to-aws
      - lint:
          requires:
            - build
      - security:
          requires:
            - build
      - test
      - build_and_push_image:
          context: *context
          requires:
            - lint
            - security
            - test
          filters:
            branches:
              only:
                - main
      - deploy_to_test_eks:
          context: *context
          requires:
            - build_and_push_image
      - editor_acceptance_tests_eks:
          context: *context
          requires:
            - deploy_to_test_eks
      - deploy_to_live_eks:
          context: *context
          requires:
            - editor_acceptance_tests_eks
          filters:
            branches:
              only:
                - main
